language: node_js
node_js:
- '0.12'
- '4.2'
- 'stable'

addons:
  postgresql: "9.4"

sudo: false

env:
  global:
  - REDIS_URL=redis://:@localhost:6379

services:
- redis-server

notifications:
  email: false

deploy:
  provider: npm
  email: me@traviswebb.com
  api_key:
    secure: AitUbALDH1eqxEuTIUMynFcaumHP2jFVZyCqUOqVmoNmHo6T5l+S6fwE1AlnPaeEic8q0gosDnMYG6W3GhQuXd0UkfAB7Gz72SHfNvNe29/svNN5exP7c/PWZZSqBxarnYM6NU7rkqdP11sF+UO6oqzd0QguT7VJPylg5EXg5I8=
  on:
    tags: true
    all_branches: true
    repo: tjwebb/sails-permissions
